### ISSUE TITLE
Constants being ignored by `IncorrectVariableCasing`

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-rpgle#108]

**Comment by worksofliam** [comment]
Cannot recreate. 

<img width="632" alt="image" src="https://user-images.githubusercontent.com/3708366/183674798-8f2479b4-1721-4470-b389-28340705b5c5.png">

**Comment by JonFP** [comment]
Interesting.

It appears that you sometimes have to request Quick Fix multiple times. Try this:

```
Dcl-C  aConstant  'A';
Dcl-S  aVariable  char(1);

aVariable = aConstant;
```
It will fix the constant name first time around and the complain about the case of the name in the Eval.  Second Quick Fix will resolve it.

When I originally reported this the case of the name was not flagged as a violation by the linter so no fix was offered.  I have since updated VS Code and now it does seem to flag the error. Just doesn't do it recursively I guess.

**Comment by JonFP** [comment]
Rather than open another issue I just found this one:

ExSr ClearSubfile;

Is incorrectly identified as a procedure call and asks for parens to be added.

**Comment by worksofliam** [comment]
@JonFP How is `ClearSubfile` defined?

**Comment by JonFP** [comment]
As a subroutine.  


Jon Paris

***@***.***

**Comment by worksofliam** [comment]
@JonFP Are you able to share a full source example so I can recreate?
