### ISSUE TITLE
Need to restart VSCODE to make the Linter active.

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-rpgle#29]
I did not have an RPGLINT.JSON file.
I started VSCODE.
I opened an RPGLE **FREE member.  No errors are reported.
I used F1 and Open RPGLE lint configuration and created a RPGLINT.JSON.
I get the "Duplicate id declaration" in problems.  (not sure if this is significant).
I switched back to the tab with the RPGLE code.   Line 4 and line 9 should have errors but none show.
![image](https://user-images.githubusercontent.com/67484051/146083638-7dafd0f2-27f7-4362-b504-cf40ae5ca401.png)
I close and reopen the member.  Still no errors.
I close the member, then close an re-start VSCODE and open the member.  And now the errors are shown:
![image](https://user-images.githubusercontent.com/67484051/146084131-193523fd-7c80-4e60-9c5a-2f638a2c5ff4.png)
If this is working as expected, then perhaps the readme needs to be updated to mention that VSCODE needs to be restarted to make the Linter active, or perhaps add a message to that effect to the dialog.

**Comment by worksofliam** [comment]
Right! I understand the error.

The issue:

1. Open some RPG. See no errors because rpglint.json does not exist.
2. Create rpglint.json (using the command palette option, which then opens the new file)
3. Switch back to RPG and the warnings still are not appearing. 

I will fix this. The work around is to force save the rpglint.json file after it's been created and it will work as expected then.

**Comment by worksofliam** [comment]
I am about to release 0.0.12 which should solve this issue.

**Comment by SJLennon** [comment]
Will test it again with 0.0.12.
